default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: data_collector_development

test:
  <<: *default
  database: data_collector_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
